<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mime-info [
  <!ELEMENT mime-info (mime-type)+>
  <!ATTLIST mime-info xmlns CDATA #FIXED "http://www.freedesktop.org/standards/shared-mime-info">

  <!ELEMENT mime-type (comment+, (acronym,expanded-acronym)? , (icon? | generic-icon? | glob | magic | treemagic | root-XML | alias | sub-class-of)*)>
  <!ATTLIST mime-type type CDATA #REQUIRED>

  <!-- a comment describing a document with the respective MIME type. Example: "WMV video" -->
  <!ELEMENT comment (#PCDATA)>
  <!ATTLIST comment xml:lang CDATA #IMPLIED>

  <!-- a comment describing the respective unexpanded MIME type acronym. Example: "WMV" -->
  <!ELEMENT acronym (#PCDATA)>

  <!-- a comment describing the respective expanded MIME type acronym. Example: "Windows Media Video" -->
  <!ELEMENT expanded-acronym (#PCDATA)>

  <!ELEMENT icon EMPTY>
  <!ATTLIST icon name CDATA #REQUIRED>

  <!-- a generic icon name as per the Icon Naming Specification, only required if computing
  it from the mime-type would not work, See "generic-icon" in the Shared Mime Specification -->
  <!ELEMENT generic-icon EMPTY>
  <!ATTLIST generic-icon name (application-x-executable|audio-x-generic|emblem-mail|emblem-symbolic-link|folder|font-x-generic|image-x-generic|media-floppy|media-optical|package-x-generic|text-html|text-x-generic|text-x-generic-template|text-x-script|video-x-generic|x-office-address-book|x-office-calendar|x-office-document|x-office-presentation|x-office-spreadsheet) #REQUIRED>

  <!ELEMENT glob EMPTY>
  <!ATTLIST glob pattern CDATA #REQUIRED>
  <!ATTLIST glob weight CDATA "50">
  <!ATTLIST glob case-sensitive CDATA #IMPLIED>

  <!ELEMENT magic (match)+>
  <!ATTLIST magic priority CDATA "50">

  <!ELEMENT match (match)*>
  <!ATTLIST match offset CDATA #REQUIRED>
  <!ATTLIST match type (string|big16|big32|little16|little32|host16|host32|byte) #REQUIRED>
  <!ATTLIST match value CDATA #REQUIRED>
  <!ATTLIST match mask CDATA #IMPLIED>

  <!ELEMENT treemagic (treematch)+>
  <!ATTLIST treemagic priority CDATA "50">

  <!ELEMENT treematch (treematch)*>
  <!ATTLIST treematch path CDATA #REQUIRED>
  <!ATTLIST treematch type (file|directory|link) #IMPLIED>
  <!ATTLIST treematch match-case (true|false) #IMPLIED>
  <!ATTLIST treematch executable (true|false) #IMPLIED>
  <!ATTLIST treematch non-empty (true|false) #IMPLIED>
  <!ATTLIST treematch mimetype CDATA #IMPLIED>

  <!ELEMENT root-XML EMPTY>
  <!ATTLIST root-XML namespaceURI CDATA #REQUIRED>
  <!ATTLIST root-XML localName CDATA #REQUIRED>

  <!ELEMENT alias EMPTY>
  <!ATTLIST alias type CDATA #REQUIRED>

  <!ELEMENT sub-class-of EMPTY>
  <!ATTLIST sub-class-of type CDATA #REQUIRED>
]>

<!--
The freedesktop.org shared MIME database (this file) was created by merging
several existing MIME databases (all released under the GNU GPL).

It comes with ABSOLUTELY NO WARRANTY, to the extent permitted by law. You may
redistribute copies of freedesktop.org.xml under the terms of the GNU General
Public License version 2 or later. For more information about these matters,
see the file named COPYING.

The latest version is available from:

        http://www.freedesktop.org/wiki/Software/shared-mime-info/

To extend this database, users and applications should create additional
XML files in the 'packages' directory and run the update-mime-database
command to generate the output files.
-->

<mime-info xmlns="http://www.freedesktop.org/standards/shared-mime-info">
  <mime-type type="application/x-atari-2600-rom">
    <comment>Atari 2600 ROM</comment>
    <generic-icon name="application-x-executable"/>
    <glob pattern="*.a26"/>
  </mime-type>
  <mime-type type="application/x-atari-7800-rom">
    <comment>Atari 7800 ROM</comment>
    <generic-icon name="application-x-executable"/>
    <glob pattern="*.a78"/>
    <magic>
      <match type="string" value="ATARI7800" offset="1"/>
    </magic>
  </mime-type>
  <mime-type type="application/x-atari-lynx-rom">
    <comment>Atari Lynx ROM</comment>
    <generic-icon name="application-x-executable"/>
    <glob pattern="*.lnx"/>
    <magic>
      <match type="string" value="LYNX" offset="0"/>
    </magic>
  </mime-type>
  <mime-type type="application/andrew-inset">
    <comment>ATK inset</comment>
    <acronym>ATK</acronym>
    <expanded-acronym>Andrew Toolkit</expanded-acronym>
    <generic-icon name="x-office-document"/>
    <glob pattern="*.ez"/>
  </mime-type>
  <mime-type type="application/epub+zip">
    <comment>Electronic book document</comment>
    <sub-class-of type="application/zip"/>
    <generic-icon name="x-office-document"/>
    <magic priority="70">
      <match type="string" value="PK\003\004" offset="0">
        <match type="string" value="mimetype" offset="30">
          <match type="string" value="application/epub+zip" offset="38"/>
          <match type="string" value="application/epub+zip" offset="43"/>
        </match>
      </match>
    </magic>
    <glob pattern="*.epub"/>
  </mime-type>
  <mime-type type="application/vnd.amazon.mobi8-ebook">
    <comment>Kindle book document</comment>
    <sub-class-of type="application/x-mobipocket-ebook"/>
    <glob pattern="*.azw3"/>
    <glob pattern="*.kfx"/>
    <alias type="application/x-mobi8-ebook"/>
  </mime-type>
  <mime-type type="application/illustrator">
    <comment>Adobe Illustrator document</comment>
    <generic-icon name="image-x-generic"/>
    <glob pattern="*.ai"/>
    <alias type="application/vnd.adobe.illustrator"/>
  </mime-type>
  <mime-type type="application/mac-binhex40">
    <comment>Macintosh BinHex-encoded file</comment>
    <sub-class-of type="text/plain"/>
    <generic-icon name="package-x-generic"/>
    <magic>
      <match type="string" value="(This file must be converted with BinHex 4.0)" offset="0"/>
      <match type="string" value="(This file must be converted; you knew that already.)" offset="0"/>
    </magic>
    <glob pattern="*.hqx"/>
  </mime-type>
  <mime-type type="application/mathematica">
    <comment>Mathematica Notebook file</comment>
    <sub-class-of type="text/plain"/>
    <generic-icon name="x-office-document"/>
    <glob pattern="*.nb" />
    <magic>
      <match value="(************** Content-type: application/mathematica"
             type="string" offset="0" />
      <match value="This notebook can be used on any computer system with Mathematica"
             type="string" offset="100:256" />
      <match value="This is a Mathematica Notebook file.  It contains ASCII text"
             type="string" offset="10:256" />
    </magic>
    <alias type="application/x-mathematica"/>
  </mime-type>
  <mime-type type="application/mathml+xml">
    <comment>MathML document</comment>
    <acronym>MathML</acronym>
    <expanded-acronym>Mathematical Markup Language</expanded-acronym>
    <alias type="text/mathml"/>
    <sub-class-of type="application/xml"/>
    <glob pattern="*.mml"/>
    <root-XML namespaceURI="http://www.w3.org/1998/Math/MathML" localName="math"/>
  </mime-type>
  <mime-type type="application/mbox">
    <comment>Mailbox file</comment>
    <generic-icon name="emblem-mail"/>
    <sub-class-of type="text/plain"/>
    <magic priority="20">
      <match type="string" value="From " offset="0"/>
    </magic>
    <glob pattern="*.mbox"/>
  </mime-type>
  <mime-type type="application/metalink+xml">
    <comment>Metalink file</comment>
    <sub-class-of type="application/xml"/>
    <magic>
      <match type="string" value="&lt;metalink version=&quot;3.0&quot;" offset="0:256"/>
    </magic>
    <glob pattern="*.metalink"/>
    <root-XML namespaceURI="http://www.metalinker.org/" localName="metalink"/>
  </mime-type>
  <mime-type type="application/metalink4+xml">
    <comment>Metalink file</comment>
    <sub-class-of type="application/xml"/>
    <magic>
      <match type="string" value="&lt;metalink xmlns=&quot;urn" offset="0:256"/>
    </magic>
    <glob pattern="*.meta4"/>
    <root-XML namespaceURI="urn:ietf:params:xml:ns:metalink" localName="metalink"/>
  </mime-type>
  <mime-type type="application/octet-stream">
    <comment>Unknown</comment>
  </mime-type>
  <mime-type type="application/x-partial-download">
    <comment>Partially downloaded file</comment>
    <generic-icon name="package-x-generic"/>
    <glob pattern="*.wkdownload"/>
    <glob pattern="*.crdownload"/>
    <glob pattern="*.part"/>
  </mime-type>
  <mime-type type="application/oda">
    <comment>ODA document</comment>
    <acronym>ODA</acronym>
    <expanded-acronym>Office Document Architecture</expanded-acronym>
    <generic-icon name="x-office-document"/>
    <glob pattern="*.oda"/>
  </mime-type>
  <mime-type type="application/x-wwf">
    <comment>WWF document</comment>
    <generic-icon name="x-office-document"/>
    <glob pattern="*.wwf"/>
    <sub-class-of type="application/pdf"/>
    <alias type="application/wwf"/>
  </mime-type>
  <mime-type type="application/pdf">
    <comment>PDF document</comment>
    <acronym>PDF</acronym>
    <expanded-acronym>Portable Document Format</expanded-acronym>
    <generic-icon name="x-office-document"/>
    <magic>
      <match type="string" value="%PDF-" offset="0:1024"/>
    </magic>
    <glob pattern="*.pdf"/>
    <alias type="application/x-pdf"/>
    <alias type="image/pdf"/>
    <alias type="application/acrobat"/>
    <alias type="application/nappdf"/>
  </mime-type>
  <mime-type type="application/xspf+xml">
    <comment>XSPF playlist</comment>
    <acronym>XSPF</acronym>
    <expanded-acronym>XML Shareable Playlist Format</expanded-acronym>
    <sub-class-of type="application/xml"/>
    <generic-icon name="audio-x-generic"/>
    <magic>
      <match type="string" value="&lt;playlist version=&quot;1" offset="0:64"/>
      <match type="string" value="&lt;playlist version='1" offset="0:64"/>
    </magic>
    <glob pattern="*.xspf"/>
    <root-XML namespaceURI="http://xspf.org/ns/0/" localName="playlist"/>
    <alias type="application/x-xspf+xml"/>
  </mime-type>
  <mime-type type="application/x-windows-themepack">
    <comment>Microsoft Windows theme pack</comment>
    <sub-class-of type="application/vnd.ms-cab-compressed"/>
    <generic-icon name="package-x-generic"/>
    <glob pattern="*.themepack"/>
  </mime-type>
  <mime-type type="audio/x-amzxml">
    <comment>AmazonMP3 download file</comment>
    <glob pattern="*.amz"/>
  </mime-type>
  <mime-type type="audio/x-gsm">
    <comment>GSM 06.10 audio</comment>
    <acronym>GSM</acronym>
    <expanded-acronym>Global System for Mobile communications</expanded-acronym>
    <glob pattern="*.gsm"/>
  </mime-type>
  <mime-type type="audio/x-iriver-pla">
    <comment>iRiver playlist</comment>
    <magic>
      <match type="string" value="iriver UMS PLA" offset="4"/>
    </magic>
    <glob pattern="*.pla"/>
  </mime-type>
  <mime-type type="application/pgp-encrypted">
    <comment>PGP/MIME-encrypted message header</comment>
    <magic>
      <match type="string" value="-----BEGIN PGP MESSAGE-----" offset="0"/>
    </magic>
    <glob pattern="*.pgp"/>
    <glob pattern="*.gpg"/>
    <glob pattern="*.asc" weight="10"/>
    <alias type="application/pgp"/>
  </mime-type>
  <mime-type type="application/pgp-keys">
    <comment>PGP keys</comment>
    <acronym>PGP</acronym>
    <expanded-acronym>Pretty Good Privacy</expanded-acronym>
    <magic>
      <match type="string" value="-----BEGIN PGP PUBLIC KEY BLOCK-----" offset="0"/>
      <match type="string" value="-----BEGIN PGP PRIVATE KEY BLOCK-----" offset="0"/>
      <match type="big16" value="0x9501" offset="0"/>
      <match type="big16" value="0x9500" offset="0"/>
      <match type="big16" value="0x9900" offset="0"/>
      <match type="big16" value="0x9901" offset="0"/>
    </magic>
    <glob pattern="*.skr"/>
    <glob pattern="*.pkr"/>
    <glob pattern="*.asc" weight="10"/>
    <glob pattern="*.pgp"/>
    <glob pattern="*.gpg"/>
    <glob pattern="*.key"/>
  </mime-type>
  <mime-type type="application/pgp-signature">
    <comment>Detached OpenPGP signature</comment>
    <magic>
      <match type="string" value="-----BEGIN PGP SIGNATURE-----" offset="0"/>
    </magic>
    <glob pattern="*.asc" weight="10"/>
    <glob pattern="*.sig"/>
    <glob pattern="*.pgp"/>
    <glob pattern="*.gpg"/>
  </mime-type>
  <!-- defined in RFC 2311 -->
  <mime-type type="application/pkcs7-mime">
    <comment>PKCS#7 file</comment>
    <acronym>PKCS</acronym>
    <expanded-acronym>Public-Key Cryptography Standards</expanded-acronym>
    <generic-icon name="text-x-generic"/>
    <glob pattern="*.p7c"/>
    <glob pattern="*.p7m"/>
  </mime-type>
  <mime-type type="application/pkcs7-signature">
    <comment>Detached S/MIME signature</comment>
    <acronym>S/MIME</acronym>
    <expanded-acronym>Secure/Multipurpose Internet Mail Extensions</expanded-acronym>
    <sub-class-of type="text/plain"/>
    <generic-icon name="text-x-generic"/>
    <glob pattern="*.p7s"/>
  </mime-type>
  <mime-type type="application/pkcs8">
    <comment>PKCS#8 private key</comment>
    <acronym>PKCS</acronym>
    <expanded-acronym>Public-Key Cryptography Standards</expanded-acronym>
    <glob pattern="*.p8"/>
  </mime-type>
  <mime-type type="application/pkcs8-encrypted">
    <comment>PKCS#8 private key (encrypted)</comment>
    <acronym>PKCS</acronym>
    <expanded-acronym>Public-Key Cryptography Standards</expanded-acronym>
    <glob pattern="*.p8e"/>
  </mime-type>
  <mime-type type="application/pkcs10">
    <comment>PKCS#10 certification request</comment>
    <acronym>PKCS</acronym>
    <expanded-acronym>Public-Key Cryptography Standards</expanded-acronym>
    <generic-icon name="text-x-generic"/>
    <glob pattern="*.p10"/>
  </mime-type>
  <mime-type type="application/pkix-cert">
    <comment>X.509 certificate</comment>
    <magic>
      <match type="string" value="-----BEGIN CERTIFICATE-----" offset="0"/>
      <match type="string" value="-----BEGIN X509 CERTIFICATE-----" offset="0"/>
    </magic>
    <glob pattern="*.cer"/>
  </mime-type>
  <mime-type type="application/pkix-crl">
    <comment>Certificate revocation list</comment>
    <magic>
      <match type="string" value="-----BEGIN X509 CRL-----" offset="0"/>
    </magic>
    <glob pattern="*.crl"/>
  </mime-type>
  <mime-type type="application/pkix-pkipath">
    <comment>PkiPath certification path</comment>
    <glob pattern="*.pkipath"/>
  </mime-type>
  <mime-type type="application/postscript">
    <comment>PostScript document</comment>
    <sub-class-of type="text/plain"/>
    <generic-icon name="x-office-document"/>
    <magic>
      <match type="string" value="\004%!" offset="0"/>
      <match type="string" value="%!" offset="0"/>
    </magic>
    <glob pattern="*.ps"/>
  </mime-type>
  <mime-type type="application/prs.plucker">
    <comment>Plucker document</comment>
    <generic-icon name="x-office-document"/>
    <magic priority="80">
      <match type="string" value="DataPlkr" offset="60"/>
    </magic>
  </mime-type>
  <mime-type type="application/buildstream+yaml">
    <comment>BuildStream element</comment>
    <sub-class-of type="application/yaml"/>
    <glob pattern="*.bst"/>
    <magic>
      <match type="string" value="kind:" offset="0:256"/>
    </magic>
  </mime-type>
  <mime-type type="application/raml+yaml">
    <comment>RAML document</comment>
    <acronym>RAML</acronym>
    <expanded-acronym>RESTful API Modeling Language</expanded-acronym>
    <sub-class-of type="application/yaml"/>
    <magic>
      <match type="string" value="#%RAML " offset="0"/>
    </magic>
    <glob pattern="*.raml"/>
  </mime-type>
  <mime-type type="application/relax-ng-compact-syntax">
    <comment>RELAX NG XML schema</comment>
    <acronym>RELAX NG</acronym>
    <expanded-acronym>REgular LAnguage for XML Next Generation</expanded-acronym>
    <sub-class-of type="text/plain"/>
    <generic-icon name="text-x-generic"/>
    <glob pattern="*.rnc"/>
    <alias type="application/x-rnc"/>
  </mime-type>
  <mime-type type="application/rtf">
    <comment>RTF document</comment>
    <acronym>RTF</acronym>
    <expanded-acronym>Rich Text Format</expanded-acronym>
    <sub-class-of type="text/plain"/>
    <generic-icon name="x-office-document"/>
    <magic>
      <match type="string" value="{\\rtf" offset="0"/>
    </magic>
    <glob pattern="*.rtf"/>
    <alias type="text/rtf"/>
  </mime-type>
  <mime-type type="application/sieve">
    <comment>Sieve mail filter script</comment>
    <generic-icon name="text-x-script"/>
    <glob pattern="*.siv"/>
    <glob pattern="*.sieve"/>
  </mime-type>
  <mime-type type="application/smil+xml">
    <comment>SMIL document</comment>
    <acronym>SMIL</acronym>
    <expanded-acronym>Synchronized Multimedia Integration Language</expanded-acronym>
    <sub-class-of type="application/xml"/>
    <alias type="application/smil"/>
    <generic-icon name="video-x-generic"/>
    <glob pattern="*.smil"/>
    <glob pattern="*.smi"/>
    <glob pattern="*.sml"/>
    <glob pattern="*.kino"/>
    <magic priority="55">
      <match type="string" value="&lt;smil" offset="0:256"/>
    </magic>
    <root-XML namespaceURI="http://www.w3.org/2001/SMIL20/Language" localName="smil"/>
    <root-XML namespaceURI="http://www.w3.org/2005/SMIL21/Language" localName="smil"/>
    <root-XML namespaceURI="http://www.w3.org/ns/SMIL" localName="smil"/>
  </mime-type>
  <mime-type type="application/vnd.ms-wpl">
    <comment>WPL playlist</comment>
    <acronym>WPL</acronym>
    <expanded-acronym>Windows Media Player Playlist</expanded-acronym>
    <generic-icon name="video-x-generic"/>
    <glob pattern="*.wpl"/>
    <magic priority="60">
      <match type="string" value="&lt;?wpl" offset="0:256"/>
    </magic>
  </mime-type>
  <mime-type type="application/x-sqlite2">
    <comment>SQLite2 database</comment>
    <glob pattern="*.sqlite2"/>
    <magic>
      <match type="string" value="** This file contains an SQLite" offset="0"/>
    </magic>
  </mime-type>
  <mime-type type="application/vnd.sqlite3">
    <comment>SQLite3 database</comment>
    <glob pattern="*.sqlite3"/>
    <magic>
      <match type="string" value="SQLite format 3" offset="0"/>
    </magic>
    <alias type="application/x-sqlite3"/>
  </mime-type>
  <mime-type type="application/x-apple-systemprofiler+xml">
    <comment>Apple System Profiler</comment>
    <sub-class-of type="application/xml"/>
    <magic>
      <match type="string" value="&lt;plist version=&quot;1.0&quot;" offset="0:256">
        <match type="string" value="&lt;key&gt;_SPCommandLineArguments&lt;/key&gt;" offset="34:384"/>
      </match>
    </magic>
    <glob pattern="*.spx" weight="40"/>
    <root-XML namespaceURI="http://www.apple.com/DTDs/PropertyList-1.0.dtd" localName="plist"/>
  </mime-type>
  <mime-type type="text/vnd.familysearch.gedcom">
    <comment>GEDCOM family history</comment>
    <acronym>GEDCOM</acronym>
    <expanded-acronym>GEnealogical Data COMmunication</expanded-acronym>
    <sub-class-of type="text/plain"/>
    <generic-icon name="x-office-document"/>
    <magic>
      <match type="string" value="0 HEAD" offset="0"/>
    </magic>
    <glob pattern="*.ged"/>
    <glob pattern="*.gedcom"/>
    <alias type="application/x-gedcom"/>
    <alias type="text/gedcom"/>
  </mime-type>
  <mime-type type="video/x-flv">
    <comment>Flash video</comment>
    <generic-icon name="video-x-generic"/>
    <magic>
      <match type="string" value="FLV" offset="0"/>
    </magic>
    <glob pattern="*.flv"/>
    <alias type="application/x-flash-video"/>
    <alias type="flv-application/octet-stream"/>
    <alias type="video/flv"/>
  </mime-type>
  <mime-type type="video/x-javafx">
    <comment>JavaFX video</comment>
    <generic-icon name="video-x-generic"/>
    <magic priority="40">
      <match type="string" value="FLV" offset="0"/>
    </magic>
    <glob pattern="*.fxm"/>
    <sub-class-of type="video/x-flv"/>
  </mime-type>
  <mime-type type="application/x-go-sgf">
    <!-- translators: a record is in this context a description of a board game
         that has been played, and that can be played back again:
         http://www.red-bean.com/sgf/ -->
    <comment>SGF record</comment>
    <acronym>SGF</acronym>
    <expanded-acronym>Smart Game Format</expanded-acronym>
    <generic-icon name="text-x-generic"/>
    <glob pattern="*.sgf"/>
    <sub-class-of type="text/plain"/>
    <magic>
      <match type="string" value="(;FF[3]" offset="0"/>
      <match type="string" value="(;FF[4]" offset="0"/>
    </magic>
  </mime-type>
  <mime-type type="application/x-godot-project">
    <comment>Godot Engine project</comment>
    <sub-class-of type="text/plain"/>
    <glob pattern="project.godot"/>
  </mime-type>
  <mime-type type="application/x-godot-resource">
    <comment>Godot Engine resource</comment>
    <glob pattern="*.res"/>
    <glob pattern="*.tres"/>
    <magic>
      <match type="string" value="[gd_resource " offset="0"/>
    </magic>
  </mime-type>
  <mime-type type="application/x-godot-scene">
    <comment>Godot Engine scene</comment>
    <glob pattern="*.scn"/>
    <glob pattern="*.tscn"/>
    <glob pattern="*.escn"/>
    <magic>
      <match type="string" value="[gd_scene " offset="0"/>
    </magic>
  </mime-type>
  <mime-type type="application/x-godot-shader">
    <comment>Godot Engine shader</comment>
    <sub-class-of type="text/plain"/>
    <glob pattern="*.gdshader"/>
  </mime-type>
  <mime-type type="application/x-gdscript">
    <comment>GDScript script</comment>
    <sub-class-of type="text/plain"/>
    <glob pattern="*.gd"/>
  </mime-type>
  <mime-type type="application/its+xml">
    <comment>ITS translation file</comment>
    <acronym>ITS</acronym>
    <expanded-acronym>Internationalization Tag Set</expanded-acronym>
    <sub-class-of type="application/xml"/>
    <generic-icon name="text-x-generic"/>
    <glob pattern="*.its"/>
    <magic>
      <match type="string" value="&lt;its" offset="0:256"/>
    </magic>
    <root-XML namespaceURI="http://www.w3.org/2005/11/its" localName="its"/>
  </mime-type>
  <mime-type type="application/xliff+xml">
    <comment>XLIFF translation file</comment>
    <acronym>XLIFF</acronym>
    <expanded-acronym>XML Localization Interchange File Format</expanded-acronym>
    <sub-class-of type="application/xml"/>
    <generic-icon name="text-x-generic"/>
    <glob pattern="*.xlf"/>
    <glob pattern="*.xliff"/>
    <magic priority="80">
      <match type="string" value="&lt;xliff" offset="0:256"/>
    </magic>
    <root-XML namespaceURI='urn:oasis:names:tc:xliff:document:1.1' localName='xliff'/>
    <alias type="application/x-xliff"/>
  </mime-type>
  <mime-type type="application/toml">
    <comment>TOML document</comment>
    <acronym>TOML</acronym>
    <expanded-acronym>Tom's Obvious Minimal Language</expanded-acronym>
    <sub-class-of type="text/plain"/>
    <generic-icon name="text-x-generic"/>
    <glob pattern="*.toml"/>
  </mime-type>
  <mime-type type="application/yaml">
    <comment>YAML document</comment>
    <acronym>YAML</acronym>
    <expanded-acronym>YAML Ain't Markup Language</expanded-acronym>
    <sub-class-of type="text/plain"/>
    <generic-icon name="text-x-generic"/>
    <magic>
      <match type="string" value="%YAML" offset="0"/>
    </magic>
    <glob pattern="*.yaml"/>
    <glob pattern="*.yml"/>
    <alias type="application/x-yaml"/>
    <alias type="text/yaml"/>
    <alias type="text/x-yaml"/>
  </mime-type>
  <mime-type type="application/vnd.corel-draw">
    <comment>Corel Draw drawing</comment>
    <generic-icon name="image-x-generic"/>
    <magic priority="80">
      <match type="string" value="CDRXvrsn" mask="0xffffff00ffffffff" offset="8"/>
    </magic>
    <glob pattern="*.cdr"/>
    <alias type="application/cdr"/>
    <alias type="application/coreldraw"/>
    <alias type="application/x-cdr"/>
    <alias type="application/x-coreldraw"/>
    <alias type="image/cdr"/>
    <alias type="image/x-cdr"/>
    <alias type="zz-application/zz-winassoc-cdr"/>
  </mime-type>
  <mime-type type="application/vnd.hp-hpgl">
    <comment>HPGL file</comment>
    <acronym>HPGL</acronym>
    <expanded-acronym>HP Graphics Language</expanded-acronym>
    <generic-icon name="image-x-generic"/>
    <glob pattern="*.hpgl"/>
  </mime-type>
  <mime-type type="application/vnd.hp-pcl">
    <comment>PCL file</comment>
    <acronym>PCL</acronym>
    <expanded-acronym>HP Printer Control Language</expanded-acronym>
    <generic-icon name="image-x-generic"/>
    <glob pattern="*.pcl"/>
  </mime-type>
  <mime-type type="application/vnd.cups-ppd">
    <comment>PostScript printer description</comment>
    <sub-class-of type="text/plain"/>
    <magic>
      <match type="string" value="*PPD-Adobe:" offset="0"/>
    </magic>
    <glob pattern="*.ppd"/>
  </mime-type>
  <mime-type type="application/vnd.lotus-1-2-3">
    <comment>Lotus 1-2-3 spreadsheet</comment>
    <generic-icon name="x-office-spreadsheet"/>
    <magic>
      <match type="string" value="\x00\x00\x02\x00\x06\x04\x06\x00\x08\x00\x00\x00\x00\x00" offset="0"/>
    </magic>
    <glob pattern="*.123"/>
    <glob pattern="*.wk1"/>
    <glob pattern="*.wk3"/>
    <glob pattern="*.wk4"/>
    <glob pattern="*.wks"/>
    <alias type="application/x-lotus123"/>
    <alias type="application/x-123"/>
    <alias type="application/lotus123"/>
    <alias type="application/wk1"/>
    <alias type="zz-application/zz-winassoc-123"/>
  </mime-type>
  <mime-type type="application/vnd.lotus-wordpro">
    <comment>Lotus Word Pro document</comment>
    <generic-icon name="x-office-document"/>
    <magic>
      <match type="string" value="WordPro" offset="0"/>
    </magic>
    <glob pattern="*.lwp"/>
  </mime-type>
  <mime-type type="application/x-lmdb">
    <comment>LMDB database</comment>
    <acronym>LMDB</acronym>
    <expanded-acronym>Lightning Memory-Mapped Database</expanded-acronym>
    <generic-icon name="x-office-document"/>
    <magic>
      <match offset="16" type="little32" value="0xBEEFC0DE" />
    </magic>
    <glob pattern="*.mdb" />
    <glob pattern="*.lmdb" />
  </mime-type>
  <mime-type type="application/vnd.ms-access">
    <comment>JET database</comment>
    <acronym>JET</acronym>
    <expanded-acronym>Joint Engine Technology</expanded-acronym>
    <generic-icon name="x-office-document"/>
    <magic>
      <match offset="0" type="string" value="\x00\x01\x00\x00Standard Jet DB" />
    </magic>
    <glob pattern="*.mdb" weight="60"/>
    <alias type="application/msaccess"/>
    <alias type="application/vnd.msaccess"/>
    <alias type="application/x-msaccess"/>
    <alias type="application/mdb"/>
    <alias type="application/x-mdb"/>
    <alias type="zz-application/zz-winassoc-mdb"/>
  </mime-type>
  <mime-type type="application/vnd.ms-cab-compressed">
    <comment>Microsoft Cabinet archive</comment>
    <generic-icon name="package-x-generic"/>
    <magic priority="60">
      <match offset="0" type="string" value="MSCF\0\0\0\0" />
    </magic>
    <glob pattern="*.cab"/>
    <alias type="zz-application/zz-winassoc-cab"/>
  </mime-type>
  <mime-type type="application/vnd.ms-excel">
    <comment>Excel spreadsheet</comment>
    <sub-class-of type="application/x-ole-storage"/>
    <generic-icon name="x-office-spreadsheet"/>
    <magic priority="60">
      <match type="string" value="\xd0\xcf\x11\xe0\xa1\xb1\x1a\xe1" offset="0">
        <match type="string" value="\x10\x08\x02\x00\x00\x00\x00\x00\xc0\x00\x00\x00\x00\x00\x00\x46" offset="592:8192"/>
        <match type="string" value="\x20\x08\x02\x00\x00\x00\x00\x00\xc0\x00\x00\x00\x00\x00\x00\x46" offset="592:8192"/>
      </match>
      <match type="string" value="Microsoft Excel 5.0 Worksheet" offset="2080"/>
    </magic>
    <glob pattern="*.xls"/>
    <glob pattern="*.xlc"/>
    <glob pattern="*.xll"/>
    <glob pattern="*.xlm"/>
    <glob pattern="*.xlw"/>
    <glob pattern="*.xla"/>
    <glob pattern="*.xlt"/>
    <glob pattern="*.xld"/>
    <alias type="application/msexcel"/>
    <alias type="application/x-msexcel"/>
    <alias type="zz-application/zz-winassoc-xls"/>
  </mime-type>
  <mime-type type="application/vnd.ms-excel.addin.macroEnabled.12">
    <comment>Excel add-in</comment>
    <generic-icon name="x-office-spreadsheet"/>
    <glob pattern="*.xlam"/>
    <sub-class-of type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"/>
  </mime-type>
  <mime-type type="application/vnd.ms-excel.sheet.binary.macroEnabled.12">
    <comment>Excel 2007 binary spreadsheet</comment>
    <generic-icon name="x-office-spreadsheet"/>
    <glob pattern="*.xlsb"/>
    <sub-class-of type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"/>
  </mime-type>
  <mime-type type="application/vnd.ms-excel.sheet.macroEnabled.12">
    <comment>Excel spreadsheet</comment>
    <generic-icon name="x-office-spreadsheet"/>
    <glob pattern="*.xlsm"/>
    <sub-class-of type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"/>
  </mime-type>
  <mime-type type="application/vnd.ms-excel.template.macroEnabled.12">
    <comment>Excel spreadsheet template</comment>
    <generic-icon name="x-office-spreadsheet"/>
    <glob pattern="*.xltm"/>
    <sub-class-of type="application/vnd.openxmlformats-officedocument.spreadsheetml.template"/>
  </mime-type>
  <mime-type type="application/vnd.ms-powerpoint">
    <comment>PowerPoint presentation</comment>
    <sub-class-of type="application/x-ole-storage"/>
    <generic-icon name="x-office-presentation"/>
    <magic priority="60">
      <match type="string" value="\xd0\xcf\x11\xe0\xa1\xb1\x1a\xe1" offset="0">
        <match type="string" value="\x10\x8d\x81\x64\x9b\x4f\xcf\x11\x86\xea\x00\xaa\x00\xb9\x29\xe8" offset="592:8192"/>
        <match type="string" value="\x70\xae\x7b\xea\x3b\xfb\xcd\x11\xa9\x03\x00\xaa\x00\x51\x0e\xa3" offset="592:8192"/>
      </match>
    </magic>
    <glob pattern="*.ppz"/>
    <glob pattern="*.ppt"/>
    <glob pattern="*.pps"/>
    <glob pattern="*.pot"/>
    <alias type="application/powerpoint"/>
    <alias type="application/mspowerpoint"/>