=== nextcloud/server/apps/dav/tests/travis/caldavtest/serverinfo.dtd
<!--
 Copyright (c) 2006-2015 Apple Inc. All rights reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 -->

<!ELEMENT serverinfo (host, path, nonsslport, sslport, unix?,
						host2?, nonsslport2?, sslport2?, unix2?,
						authtype?, waitcount?, waitdelay?, waitsuccess?,
						features?, substitutions)? >

	<!ELEMENT host			(#PCDATA)>
	<!ELEMENT path			(#PCDATA)>
	<!ELEMENT nonsslport	(#PCDATA)>
	<!ELEMENT sslport		(#PCDATA)>
	<!ELEMENT unix			(#PCDATA)>
	<!ELEMENT host2			(#PCDATA)>
	<!ELEMENT nonsslport2	(#PCDATA)>
	<!ELEMENT sslport2		(#PCDATA)>
	<!ELEMENT unix2			(#PCDATA)>
	<!ELEMENT authtype		(#PCDATA)>
	<!ELEMENT waitdelay     (#PCDATA)>
	<!ELEMENT waitcount     (#PCDATA)>
	<!ELEMENT waitsuccess   (#PCDATA)>
	<!ELEMENT features      (feature*)>
		<!ELEMENT feature   (#PCDATA)>
	<!ELEMENT substitutions	(substitution|repeat)*>
		<!ELEMENT repeat	(substitution+)>
    		<!ATTLIST repeat count CDATA "1">
		<!ELEMENT substitution	(key, value)>
			<!ELEMENT key			(#PCDATA)>
			<!ELEMENT value			(#PCDATA)>

=== nextcloud/server/apps/dav/tests/travis/caldavtest/serverinfo-old-caldav-endpoint.xml
<?xml version="1.0" standalone="no"?>

<!DOCTYPE serverinfo SYSTEM
		"/home/deepdiver/Development/ownCloud/master/apps/dav/tests/travis/caldavtest/serverinfo.dtd">

<!--
 Copyright (c) 2006-2015 Apple Inc. All rights reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 -->

<serverinfo>
	<host>localhost</host>
	<nonsslport>8888</nonsslport>
	<authtype>basic</authtype>
	<!-- <unix>/tmp/caldavd_requests/unsecured.sock</unix> -->

	<waitcount>120</waitcount>
	<waitdelay>0.25</waitdelay>
	<waitsuccess>30</waitsuccess>

	<features>
		<!--  Generic WebDAV extensions -->
		<feature>COPY Method</feature>							<!-- COPY method -->
		<feature>MOVE Method</feature>							<!-- MOVE method -->
		<feature>Extended MKCOL</feature>						<!-- Extended MKCOL -->

		<!-- ACL related -->
		<feature>ACL Method</feature>							<!-- ACL method -->
		<feature>acl-principal-prop-set REPORT</feature>		<!-- ACL acl-principal-prop-set REPORT -->
		<feature>principal-match REPORT</feature>				<!-- ACL principal-match REPORT -->
		<feature>principal-property-search REPORT</feature>		<!-- ACL principal-property-search REPORT -->
		<feature>principal-search-property-set REPORT</feature>	<!-- ACL principal-search-property-set REPORT -->
		<feature>calendarserver-principal-search REPORT</feature>	<!-- ACL calendarserver-principal-search REPORT -->

		<feature>add-member</feature>					<!-- Add-member used to create resources -->
		<!-- <feature>auth-on-root</feature> -->		<!-- Whether the server requires authentication on the root URI -->
		<feature>brief</feature>					    <!-- Brief header for PROPFIND, REPORT -->
		<feature>bulk-post</feature>					<!-- Bulk POST requests -->
		<feature>ctag</feature>							<!-- ctag extension -->
		<feature>current-user-principal</feature>		<!-- current-user-principal extension -->
		<feature>directory listing</feature> 			<!-- GET on collection -->
		<feature>extended-principal-search</feature>	<!-- Extended principal-property-search REPORT extension -->
		<feature>expand-property</feature>				<!-- Expand property REPORT -->
		<feature>only-proxy-groups</feature>			<!-- Group-membership only includes delegated-to groups -->
		<feature>limits</feature>						<!-- max-collections and max-resources limits -->
		<feature>own-root</feature>						<!-- / is owned by this service -->
		<feature>prefer</feature>						<!-- Prefer header overall support -->
		<feature>prefer-minimal</feature>				<!-- Prefer header return=minimal -->
		<feature>prefer-representation</feature>		<!-- Prefer header return=representation -->
		<feature>prefer-noroot</feature>				<!-- Prefer header depth-noroot -->
		<feature>quota</feature>						<!-- WebDAV QUOTA -->
		<!-- <feature>quota-on-resources</feature> -->	<!-- WebDAV QUOTA on calendar and address book object resources -->
		<feature>resource-id</feature>					<!-- WebDAV BIND DAV:resource-id property -->
		<feature>sync-report</feature>					<!-- WebDAV collection sync REPORT -->
		<!-- <feature>sync-report-limit</feature> -->	<!-- WebDAV collection sync REPORT DAV:limit support -->
		<!--<feature>sync-report-home</feature>				&lt;!&ndash; WebDAV collection sync REPORT on Homes &ndash;&gt;-->
		<feature>sync-report-config-token</feature>		<!-- Sync REPORT token includes configuration component -->
		<feature>well-known</feature>					<!-- well-known feature -->

		<!-- <feature>per-object-ACLs</feature> -->		<!-- ACL for objects in calendar/address books -->
		<!-- <feature>regular-collection</feature> -->  <!-- Regular collections allowed in calendar/address book homes -->

		<feature>json-data</feature>					<!-- jCal and jCard support -->

		<!--  CalendarServer specific extensions -->
		<feature>control-api</feature>					<!-- Control API support -->

		<!-- CalDAV specific extension -->
		<feature>caldav</feature>					    <!-- Basic CalDAV feature enabler -->
		<feature>attachments-collection</feature>		<!-- Server uses a collection in same WebDAV tree to store attachments -->
		<feature>auto-accept</feature>					<!-- Auto-accept for rooms & locations -->
		<feature>auto-accept-modes</feature>			<!-- Auto-accept modes -->
		<feature>client-fix-TRANSP</feature>			<!-- fix client TRANSP -->
		<!-- <feature>dropbox</feature> -->				<!-- dropbox extension -->
		<feature>default-alarms</feature>				<!-- default alarms extension -->
		<feature>EMAIL parameter</feature>				<!-- Server normalizes cuaddress and adds EMAIL parameter -->
		<feature>extended-freebusy</feature>	      	<!-- Extended freebusy response -->
		<feature>freebusy-url</feature>	      			<!-- Freebusy URL -->
		<feature>group-attendee-expansion</feature>	    <!-- Auto-expansion of group attendees -->
		<feature>implicit-scheduling</feature>			<!-- CalDAV scheduling - implicit -->
		<feature>location-resource-tracking</feature>   <!-- Server tracks who makes unscheduled changes to locations and resources -->
		<feature>managed-attachments</feature>			<!-- CalDAV Managed Attachments -->
		<feature>maskuid</feature>						<!-- maskuid extension -->
		<feature>no-duplicate-uids</feature>			<!-- duplicate UIDs in same home not supported -->
		<feature>partstat-timestamp</feature>			<!-- Time stamps when PARTSTAT changes extension -->
		<!-- <feature>podding</feature> -->  			<!-- Podded server -->
		<feature>private-comments</feature>				<!-- private-comments extension -->
		<feature>private-events</feature>				<!-- private-events extension -->
		<feature>proxy</feature>						<!-- calendar-user-proxy extension -->
		<!-- <feature>proxy-authz</feature> -->			<!-- sudo user extension -->
		<feature>recurrence-splitting</feature>			<!-- Recurring components can be split -->
		<feature>remove-duplicate-alarms</feature>   	<!-- Server removes any duplicate alarms on PUT -->
		<feature>query-extended</feature>				<!-- calendar-query-extended extension -->
		<feature>shared-calendars</feature>				<!-- Shared calendars extension -->
		<feature>share-calendars-to-groups</feature>	<!-- Share calendars to groups extension -->
		<feature>schedule-changes</feature>				<!-- schedule-changes property extension -->
		<feature>split-calendars</feature>				<!-- Calendars are split by component type -->
		<feature>supported-component-sets</feature>		<!-- CALDAV:supported-calendar-component-sets on calendar homes -->
		<feature>supported-component-sets-one</feature>	<!-- Only single component calendars allowed to be created -->
		<feature>timerange-low-limit</feature>			<!-- Time-range only valid one year back -->
		<feature>timerange-high-limit</feature>			<!-- Time-range only valid 5 years ahead -->
		<feature>timezones-by-reference</feature>		<!-- Timezones by reference enabled -->
		<feature>timezone-service</feature>				<!-- Timezone service extension for Wiki -->
		<feature>timezone-std-service</feature>			<!-- Timezone standard service extension -->
		<!-- <feature>trash-collection</feature> -->  			<!-- Trash collection enabled -->
		<feature>travel-time-busy</feature> 			<!-- Travel time appears as busy -->
		<feature>vavailability</feature>				<!-- VAVAILABILITY on inbox -->
		<!-- <feature>vpoll</feature> -->				<!-- VPOLL support for store and scheduling -->
		<feature>webcal</feature>						<!-- Internet calendar subscription via GET on calendar collection -->

		<!-- CardDAV specific extension -->
		<feature>carddav</feature> 						<!-- Basic CardDAV feature enabler -->
		<feature>default-addressbook</feature> 			<!-- Default address book behavior -->
		<feature>shared-addressbooks</feature>			<!-- Shared address books extension -->
		<feature>shared-addressbook-groups</feature>	<!-- Shared address book groups extension -->
		<feature>directory-gateway</feature>			<!-- Directory gateway extension -->

	</features>

	<substitutions>
		<!-- Useful xpath shortcuts for verifiers -->
		<substitution>
			<key>$multistatus-response-prefix:</key>
			<value>/{DAV:}multistatus/{DAV:}response</value>
		</substitution>
		<substitution>
			<key>$multistatus-href-prefix:</key>
			<value>/{DAV:}multistatus/{DAV:}response/{DAV:}href</value>
		</substitution>
		<substitution>
			<key>$verify-response-prefix:</key>
			<value>{DAV:}response/{DAV:}propstat/{DAV:}prop</value>
		</substitution>
		<substitution>
			<key>$verify-property-prefix:</key>
			<value>/{DAV:}multistatus/{DAV:}response/{DAV:}propstat/{DAV:}prop</value>
		</substitution>
		<substitution>
			<key>$verify-bad-response:</key>
			<value>/{DAV:}multistatus/{DAV:}response/{DAV:}status</value>
		</substitution>
		<substitution>
			<key>$verify-error-response:</key>
			<value>/{DAV:}multistatus/{DAV:}response/{DAV:}error</value>
		</substitution>
		<substitution>
			<key>$CALDAV:</key>
			<value>urn:ietf:params:xml:ns:caldav</value>
		</substitution>
		<substitution>
			<key>$CARDDAV:</key>
			<value>urn:ietf:params:xml:ns:carddav</value>
		</substitution>
		<substitution>
			<key>$CS:</key>
			<value>http://calendarserver.org/ns/</value>
		</substitution>

		<!-- Server configuration settings -->
		<!-- $host: and $hostssl: are implicitly added by CalDAVTester based
		     on the host/nonsslport/sslport values and ssl command line switch -->

		<!-- relative path to caldav root-->
		<substitution>
			<key>$root:</key>
			<value>/remote.php/caldav/</value>
		</substitution>

		<!-- relative path to main principal collection-->
		<substitution>
			<key>$principalcollection:</key>
			<value>$root:principals/</value>
		</substitution>

		<!-- the core recored type collections-->
		<substitution>
